- Dockerfile
Related issues: danpoltawski/docker-moodle#9.
> Fix TMP permissions to avoid UPLOAD_ERR_NO_TMP_DIR.

- root/tmp/setup/php-extensions.sh
> Don't remove apt https transport after build

- Dockerfile
Recently the official builds moved the default from jessie to stretch
so, some of the dependencies in our container stopped working.
This just ensures that we continue using the -jessie variants until
the move to -stretch (and dependencies) are tested enough.
Part of #21.
> Explicitly use -jessie as base until we move to -stretch

- README.md
- root/tmp/setup/sqlsrv-extension.sh
(just reconciling the tags in all branches)
> 7.3-stretch versions cleanup

- README.md
- root/tmp/setup/php-extensions.sh
(just reconciling the tags in all branches)
> 7.1-stretch versions cleanup

- root/usr/local/etc/php/conf.d/mdl-65594.ini
This commit disables pcre.jit. Unfortunately this is not easy to do at runtime due to the fact that mounting individual files in docker has limited support. This addresses segfaults discovered in MDL-65594.
> 7.1 stretch pcrejit

- root/tmp/setup/php-extensions.sh
- root/tmp/setup/solr-extension.sh
- tests/fixtures/test.php
Using 2.4.0 release + custom patch (from macports project) seems to
be the only working combination right now. Read the comments in the code
and the links there.
Resolves solr issue in #16, waiting for the upstream as described in #19
> Install solr extension from source

- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
Just that, nothing else needs to be done. moolde-docker will have
other changes to make the test environment ready.
This is part of #16 
Unit tests are passing ok with 37_STABLE and master:
````
$ bin/moodle-docker-compose exec webserver vendor/bin/phpunit --testsuite cachestore_mongodb_testsuite -v
Moodle 3.8dev (Build: 20190524), 383aec8a01942b09326119e4c2119aa982925312
Php: 7.3.5, pgsql: 9.6.7, OS: Linux 4.9.125-linuxkit x86_64
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.5
Configuration: /var/www/html/phpunit.xml
..                                                                  2 / 2 (100%)
Time: 4.46 seconds, Memory: 50.00 MB
OK (2 tests, 42 assertions)
````
And being skipped with previous Moodle versions (where …
> Enable the mongodb extension for 7.3

- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
Just that, nothing else needs to be done. moolde-docker will have
other changes to make the test environment ready.
This is part of #16 
Unit tests are passing ok with 37_STABLE and master:
````
$ bin/moodle-docker-compose exec webserver vendor/bin/phpunit --testsuite cachestore_mongodb_testsuite -v
Moodle 3.7+ (Build: 20190524), e39f3b7db215b61d68ea2a23ff850f0efa1853e8
Php: 7.2.18, pgsql: 9.6.7, OS: Linux 4.9.125-linuxkit x86_64
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.2.18
Configuration: /var/www/html/phpunit.xml
..                                                                  2 / 2 (100%)
Time: 4 seconds, Memory: 52.00 MB
OK (2 tests, 42 assertions)
````
And being skipped with previous Moodle versions (where …
> Enable the mongodb extension for 7.2

- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
In this branch we had to, also, install the extension. Was not present.
Just that, nothing else needs to be done. moolde-docker will have
other changes to make the test environment ready.
This is part of #16 
Unit tests are passing ok with 37_STABLE and master:
````
$ bin/moodle-docker-compose exec webserver vendor/bin/phpunit --testsuite cachestore_mongodb_testsuite -v
Moodle 3.7+ (Build: 20190524), e39f3b7db215b61d68ea2a23ff850f0efa1853e8
Php: 7.1.29, pgsql: 9.6.7, OS: Linux 4.9.125-linuxkit x86_64
PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.29
Configuration: /var/www/html/phpunit.xml
..                                                                  2 / 2 (100%)
Time: 4.78 seconds, Memory: 52.00 MB
OK (2 tests, 42 assertions
````
And being skipped with …
> Install and enable the mongodb extension for 7.1

- root/usr/local/etc/php/conf.d/mdl-65594.ini
We are getting a good number of segmentation faults in the
new jobs (lowest) using php70 and have found various reports about
the pcre jit compiler also causing problems with php70.
So, proceeding (and crossing fingers).
> Exactly the same than php71's #56, but applied to php70

- root/tmp/setup/php-extensions.sh
> Let's remain sticky to Redis 4.3.0

- root/tmp/setup/php-extensions.sh
> Let's remain sticky to Redis 4.3.0 (php73-buster)

- root/tmp/setup/php-extensions.sh
> Let's remain sticky to Redis 4.3.0 (php71)

- root/tmp/setup/php-extensions.sh
> Let's remain sticky to Redis 4.3.0  (php72)

- root/tmp/setup/php-extensions.sh
> Let's remain sticky to Redis 4.3.0 (php73)

- root/tmp/setup/php-extensions.sh
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.0-stretch)

- root/tmp/setup/php-extensions.sh
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.1-buster)

- root/tmp/setup/php-extensions.sh
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.1-stretch)

- root/tmp/setup/php-extensions.sh
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.2-buster)

- root/tmp/setup/php-extensions.sh
Once https://tracker.moodle.org/browse/MDL-66139 is rolled. Part ot #77
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.2-stretch)

- root/tmp/setup/php-extensions.sh
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.3-buster)

- root/tmp/setup/php-extensions.sh
> Unpin Redis 4.3.0. Newer >= 5.0.0 versions should be back to work (7.3-stretch)

- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
(will help completing https://github.com/moodlehq/moodle-docker/issues/110)
> Add the uuid extension. Some tests use it - 7.1-buster

- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
(will help completing https://github.com/moodlehq/moodle-docker/issues/110)
> Add the uuid extension. Some tests use it - 7.3-stretch

- root/tmp/setup/php-extensions.sh
Only was affecting 35_STABLE, I don't understand / remember
why. The very same php70 image (using solr 2.5.0) is passing
perfectly with 36_STABLE.
In any case, downgrading fixes it and given, php70 is EOL, this
quick fix is enough to get 35_STABLE back to pass.
> Make php70 solr extension sticky to 2.4.0

- Dockerfile
- README.md
- hooks/post_push
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
- tests/fixtures/test.php
with the release of 7.4.0 we can now make 7.4-buster (and 7.4) public. So creating the branch and adding all the stuff.
> 7.4 buster

- root/tmp/setup/oci8-extension.sh
- root/tmp/setup/sqlsrv-extension.sh
- sqlsrv: bump to current stable sqlsrv-5.8.1
- oci: switch to current instantclient from oracle official public site.
Note that this doesn't fix MDL-68655, php74 + oracle problems
with this docker image continue happening the same. Follow the
issue for more information.
> Minor updates to sqlsrv and oci drivers

- Dockerfile
> Finally add git to the PHP image (71-buster)

- Dockerfile
> Finally add git to the PHP image (72-buster)

- Dockerfile
> Finally add git to the PHP image (73-buster)

- Dockerfile
> Finally add git to the PHP image (74-buster)

- Dockerfile
> Finally add git to the PHP image (70-stretch)

- Dockerfile
- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
Link: https://pecl.php.net/package/xmlrpc
Note: RC1 had a packaging bug making it unusable, see https://bugs.php.net/bug.php?id=80618
Also, bump to 8.0.1
> Adding xmlrpc-beta now that 1.0.0RC2 has been released

- Dockerfile
(by moving to 8.0-apache-buster "floating" tag)
Note this is just to reconcile master with the more modern version available, that is 8.0-buster right now.
Please merge this at very least 1-hour after merging #128. This is a requirement to verify one thing about the default description shown @ https://hub.docker.com/r/moodlehq/moodle-php-apache
1. When #128 is merged and DockerHub builds it... then the description is the 8.0-buster one.
2. 1 hour later, when this is merged and DockerHub builds this... then the description is back to the (complete, all versions) master one.
Just need to confirm this behavior to finish some auto-builders that will be in charge of schedule rebuilds of the images, planning to, always, put master the last one in order to get the complete description as is …
> Bump to php 8.0.2

- root/tmp/setup/php-extensions.sh
Add support for pcov such that we may generate code coverage with relative ease.
> Add support for pcov

- .github/workflows/test_buildx_and_publish.yml
- Dockerfile
- README.md
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
Note we still keep buster as default, so this only will build
the 7.4-bullseye tag.
Part of https://github.com/moodlehq/moodle-php-apache/issues/136
Creating the PR because it's passing tests locally and would be great to have it available to run a battery of DEV jobs @ ci.moodle.org and verify that everything is ok.
Once that's checked... another PR will switch defaults, making bullseye the new default one, relegating buster to 2nd line.
> First php 7.4 debian bullseye (11) build

- .github/workflows/test_buildx_and_publish.yml
- Dockerfile
- README.md
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
Note we still keep buster as default, so this only will build
the 8.0-bullseye tag.
Part of https://github.com/moodlehq/moodle-php-apache/issues/136
Creating the PR because it's passing tests locally and would be great to have it available to run a battery of DEV jobs @ ci.moodle.org and verify that everything is ok.
Once that's checked... another PR will switch defaults, making bullseye the new default one, relegating buster to 2nd line.
> First php 8.0 debian bullseye (11) build

- Dockerfile
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
This change makes it much faster to make smaller changes to the image by:
- moving the ADD commands to more targeted additions in order of build size
- breaking out the Oracle and sqlsrv builds into their own ADD and RUN sections in the Dockerfile
- moving the addition of non build-related files to right at the end of the Dockerfile
These changes mean that it is possible to more easily develop the image, for example:
- you can now make changes to files within the /usr directory without recompiling all PHP extensions
- you can now iterate on the Oracle and/or sqlsrv extensions without recompiling all PHP extensinos
- you can now iterate on the sqlsrv extension, without recompiling all PHP extensions, or Oracle
Whist this has little effect on the end image, or the build process within CI …
> Streamline the build of the image

- .github/workflows/test_buildx_and_publish.yml
- Dockerfile
- README.md
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
- root/usr/local/bin/moodle-docker-php-entrypoint
- tests/docker-entrypoint.d/20-example.ini
- tests/docker-entrypoint.d/30-sourced.sh
- tests/docker-entrypoint.d/40-exec.sh
- tests/fixtures/check-entrypoint-scripts.php
- tests/fixtures/check-ini.php
This commit adds support for run-time configuration which is executed as part of the startup of the container.
Two options are supported:
* shell scripts; and
* .ini files for PHP configuration.
These can be placed into a new directory, located at /docker-entrypoint-initdb.d and files are executed in lexical order returned by a bash glob.
> Add support for entrypoint scripts

- Dockerfile
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
- tests/fixtures/test.php
This change removes MongoDB from our build.
This change is only suitable for PHP 8.2, because older versions of PHP are used in older versions of Moodle where MongoDB still exists. We support MongoDB for Moodle 4.1 and older.
> Remove MongoDB

- Dockerfile
- root/tmp/setup/php-extensions.sh
- root/tmp/setup/sqlsrv-extension.sh
The `msodbcsql18` package is now available under the MS Bullseye repository, and they've added support for some new architectures.
The new `Release` file offers the following architecture support:
```
Architectures: amd64 arm64 armhf all
```
I'm not sure on how the driver version may affect us, but according to the (SQL version compatibility table)[https://learn.microsoft.com/en-us/sql/connect/odbc/windows/system-requirements-installation-and-driver-files?view=sql-server-ver16]:
- msodbcsql17 supports SQL Server 2012 and up
- msodbcsql18 18.0 supports SQL Server 2014 and up
- msodbcsql18 18.1 supports SQL Server 2014 and up
At the same time, Moodle 3.10 dropped support for SQL Server 2012.
Moodle 3.9 only supports PHP 7.2 - PHP 7.4.
Moodle 3.11 supports PHP 7.3 - 8.0
Moodle 4.00 supports …
> Build sqlsrv for ARM architectures too

- .github/workflows/test_buildx_and_publish.yml
- README.md
- root/usr/local/bin/moodle-docker-php-entrypoint
- root/usr/local/bin/moodle-docker-php-ini
- tests/fixtures/check-ini.php
This adds a layer of common sense on top of the other changes I've worked on to allow easy configuration variable setting.
This is currently based on top of #162 and #163 together, but can be refactored easily.
The tl;dr is:
```
docker run \
--name web0 \
-p 8080:80 \
-v $PWD/moodle:/var/www/html
-e INI-upload_max_filesize=200M \
-e INI-post_max_size=210M \
moodle-php-apache:latest
```
Will cause a new php.ini file to be created at `/usr/local/etc/php/conf.d/10-local.ini containing:
```
upload_max_filesize = 200M
post_max_size = 210M
```
> Add simple environment-based PHP configuration

- .github/workflows/test_buildx_and_publish.yml
- root/usr/local/bin/moodle-docker-php-ini
- root/usr/local/etc/php/conf.d/10-docker-php-moodle.ini
- tests/fixtures/check-ini.php
This increases the standard maximum upload file size to 200M, which is a much more realistic size for development.
This also requires a bump in the maximum post size.
> Increase max upload size

- Dockerfile
- root/tmp/setup/locales-gen.sh
- root/tmp/setup/php-extensions.sh
When trying to modify the php installed extensions in the images it's a pain to have to wait for all the locales to be generated.
So, the changes here just split that responsibility to another, separated layer that will be cached before playing with extensions.
If accepted, I'll spread the change over all the versions... 
Ciao :-)
> Split locales generation out from php extensions installation

- .github/workflows/test_buildx_and_publish.yml
- README.md
- root/tmp/setup/php-extensions.sh
- root/usr/local/bin/moodle-docker-php-ini
- tests/fixtures/check-ini.php
This also adds a new PHP_EXTENSION-[name]=1 environment variable optino to call docker-php-ext-enable on start.
> Install xdebug and xhprof as standard

- root/tmp/setup/php-extensions.sh
- tests/fixtures/test.php
It comes disabled by default and Moodle does support to use it as alternative serializer. Covered with test.
Fixes #182
Once this is accepted I'll backport this to all PHP 8.0, 8.1 and 8.2 images.
> Enable igbinary serializer for redis

- root/tmp/setup/php-extensions.sh
1.20.0 introduced a breaking changes, so we need to stick with 1.19.4
> Pin mongodb extension to 1.19.4

- Dockerfile
- root/etc/apache2/conf-enabled/fallback.conf
Needs to be applied to 8.1, 8.2, and 8.3.
> Use the Moodle Router as a FallbackResource
